### ISSUE TITLE
How to test BULK/IN endpoint?

### ISSUE THREAD

**Issue by forderud** [xxandy/USB_UDE_Sample#19]
I've so far managed to INTERRUPT/IN endpoint triggered through `DeviceIoControl` calls. I've also managed to get the BULK/OUT endpoint working through `WriteFile` calls.

However, calling `ReadFile` to test the BULK/IN endpoint doesn't seem to work. The call is just deadlocking after leaving a "BCHAN Mission request xxxxxxxx pended" traceView event. Is this expected behavior?

**Comment by xxandy** [comment]
That path is fully exercised by the test tool (along with all valid combinations).
From your comment in the pull request, it looks like you were already able to run the tool - is that not true?

**Comment by xxandy** [comment]
So I went through the code and refreshed my memory a bit.

Did you notice that you need to have two running instances of the test application running at the same time, in order to exercise all paths?

From the readme:

1 - first instance 
hostudetest.exe -a (goes into a loop waiting for commands over USB. Those can be sent from a separate instance, with the -c flag)

2 - second instance - runs while the first one stays resident, and waiting for the so-called "missions", which are sent via USB.  The mission "response" (which is what comes via BULK/IN) will not arrive unless the instance 1 above makes a request to respond...
hostudetest.exe -c somemission

**Comment by xxandy** [comment]
were you able to test this okay with two instances of the hostudetest.exe app?

**Comment by forderud** [comment]
Thanks for the suggestions Alex. Using `hostudetest.exe -a` together with `hostudetest.exe -c somemission` I was able to trigger the UDEFX2 `BackChannelEvtRead` callback, which logged "BCHAN Mission request %p pended" _without_ deadlocking. This is indeed a good starting point for better understanding the implementation.

Do you know if it's also possible to trigger the UDEFX2 `BackChannelEvtRead` "BCHAN Mission request %p filed with pre-existing data" path from hostudetest?

**Comment by xxandy** [comment]
hi, in order to trigger the  "BCHAN Mission request %p filed with pre-existing data" path , the following would have to happen, in order:

1.  IoEvtBulkOutUrb() is called (in response to USB data being sent OUT) , triggering the path  , "Mission request %p enqueued" ,  which leaves an entry pending in pBackChannelContext->missionRequest .
2. Some time later, BackChannelEvtRead() is called , which will fetch that request from pControllerContext->missionRequest  (same queue), and result in the codepath you mentioned.


However, the code paths triggered by the pair of hostudetest.exe -a / -c  is always the reverse order as the above, which results in the read being pended prior to the write coming in and completing it.

This is because you run hostudetest -a  first, and that  initiates a read from the backchannel, as its first step (#2 above). See testapp.c: AutoBot() , where it calls ReadFile, against the back-channel driver.

I suspect (but I don't have the environment to test now) that if you just reverse the order of hostudetest.exe -a / -c  (use the  `-c somemission` commandline first),  you may be able to trigger that code path.

**Comment by forderud** [comment]
Thanks for very useful suggestions. I've now successfully managed to reproduce the "BCHAN Mission request %p filed with pre-existing data" path. Will therefore close the issue.
