### ISSUE TITLE
Interest in porting drivers to C++?

### ISSUE THREAD

**Issue by forderud** [xxandy/USB_UDE_Sample#34]
No sure if there's any appetite for it, but I can help out porting the drivers to the subset of C++ that is safe for kernel-mode drivers?

The biggest benefit will likely be RAII wrappers to automate resource cleanup, so that one can get rid of most of the `goto` statements.

**Comment by xxandy** [comment]
I am interested, but I think that would be nice in a forked project.  It will be nice for someone learning to be able to see the difference, and to still have the C version around - which takes a little bit less memory (I think) from not linking c++ libraries.

By the way, if we start to get into "new work" areas, my top of mind would be to run Driver Verifier, and fix any issues detected by that. Last time I ran it, long ago, it seems there was an assert - and I didn't bother fixing, because everything "just works".   Fixing that would probably be desirable prior to forking for a C++ version.

**Comment by forderud** [comment]
> I am interested, but I think that would be nice in a forked project. It will be nice for someone learning to be able to see the difference, and to still have the C version around - which takes a little bit less memory (I think) from not linking c++ libraries.

Neither the C++ standard library nor exception are accessible in kernel-mode. I therefore don't think a C++ port will trigger any code bloat - at least not due to those reasons. Still, I'll then focus my work on other areas than C to C++ porting.

> By the way, if we start to get into "new work" areas, my top of mind would be to run Driver Verifier, and fix any issues detected by that. Last time I ran it, long ago, it seems there was an assert - and I didn't bother fixing, because everything "just works". Fixing that would probably be desirable prior to forking for a C++ version.

Good point. Will take a look at it when time permits.
